import 'package:app_test1/components/end_drawer_perso.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/material.dart';

class PageBoutique extends StatefulWidget {
  const PageBoutique({super.key});

  @override
  State<PageBoutique> createState() => _PageBoutiqueState();
}

class _PageBoutiqueState extends State<PageBoutique> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      endDrawer: EndDrawerPerso(),
      appBar: AppBar(
        title: const Text("Page Boutique"),
        backgroundColor: Theme.of(context).appBarTheme.backgroundColor,
        foregroundColor: Theme.of(context).appBarTheme.foregroundColor,
      ),
      body: Center(
        child: Container(
          width: double.infinity,
          child: Column(
            children: [
              SizedBox(
                height: 150,
                child: Container(
                  width: double.infinity,
                  child: CarouselSlider(
                    items: const [
                      Image(
                        image: AssetImage("assets/images/1.jpg"),
                        fit: BoxFit.fill,
                      ),
                      Image(
                        image: AssetImage("assets/images/1.jpg"),
                        fit: BoxFit.fill,
                      ),
                      Image(
                        image: AssetImage("assets/images/1.jpg"),
                        fit: BoxFit.fill,
                      ),
                    ],
                    options: CarouselOptions(
                      autoPlay: true,
                      enlargeCenterPage: true,
                      viewportFraction: 0.5,
                      aspectRatio: 1.5,
                      enlargeFactor: 0.5,
                    ),
                  ),
                ),
              ),
              Expanded(
                child: SafeArea(
                  bottom: true,
                  child: Container(
                    width: double.infinity,
                    margin: const EdgeInsets.all(5),
                    decoration: BoxDecoration(
                      border: Border.all(
                        width: 2,
                        color: Theme.of(context).colorScheme.primary,
                      ),
                      borderRadius: BorderRadius.circular(10),
                    ),
                    child: SingleChildScrollView(
                      child: Column(
                        children: const [
                          Text("Produit 1"),
                          Text("Produit 2"),
                          Text("Produit 3"),
                          Text("Produit 4"),
                          Text("Produit 5"),
                          Text("Produit 6"),
                          Text("Produit 7"),
                          Text("Produit 8"),
                          Text("Produit 9"),
                          Text("Produit 10"),
                          Text("Produit 11"),
                          Text("Produit 12"),
                          Text("Produit 13"),
                          Text("Produit 14"),
                          Text("Produit 15"),
                          Text("Produit 16"),
                          Text("Produit 17"),
                          Text("Produit 18"),
                          Text("Produit 19"),
                          Text("Produit 20"),     Text("Produit 1"),
                          Text("Produit 2"),
                          Text("Produit 3"),
                          Text("Produit 4"),
                          Text("Produit 5"),
                          Text("Produit 6"),
                          Text("Produit 7"),
                          Text("Produit 8"),
                          Text("Produit 9"),
                          Text("Produit 10"),
                          Text("Produit 11"),
                          Text("Produit 12"),
                          Text("Produit 13"),
                          Text("Produit 14"),
                          Text("Produit 15"),
                          Text("Produit 16"),
                          Text("Produit 17"),
                          Text("Produit 18"),
                          Text("Produit 19"),
                          Text("Produit 20"),     Text("Produit 1"),
                          Text("Produit 2"),
                          Text("Produit 3"),
                          Text("Produit 4"),
                          Text("Produit 5"),
                          Text("Produit 6"),
                          Text("Produit 7"),
                          Text("Produit 8"),
                          Text("Produit 9"),
                          Text("Produit 10"),
                          Text("Produit 11"),
                          Text("Produit 12"),
                          Text("Produit 13"),
                          Text("Produit 14"),
                          Text("Produit 15"),
                          Text("Produit 16"),
                          Text("Produit 17"),
                          Text("Produit 18"),
                          Text("Produit 19"),
                          Text("Produit 20"),     Text("Produit 1"),
                          Text("Produit 2"),
                          Text("Produit 3"),
                          Text("Produit 4"),
                          Text("Produit 5"),
                          Text("Produit 6"),
                          Text("Produit 7"),
                          Text("Produit 8"),
                          Text("Produit 9"),
                          Text("Produit 10"),
                          Text("Produit 11"),
                          Text("Produit 12"),
                          Text("Produit 13"),
                          Text("Produit 14"),
                          Text("Produit 15"),
                          Text("Produit 16"),
                          Text("Produit 17"),
                          Text("Produit 18"),
                          Text("Produit 19"),
                          Text("Produit 20"),     Text("Produit 1"),
                          Text("Produit 2"),
                          Text("Produit 3"),
                          Text("Produit 4"),
                          Text("Produit 5"),
                          Text("Produit 6"),
                          Text("Produit 7"),
                          Text("Produit 8"),
                          Text("Produit 9"),
                          Text("Produit 10"),
                          Text("Produit 11"),
                          Text("Produit 12"),
                          Text("Produit 13"),
                          Text("Produit 14"),
                          Text("Produit 15"),
                          Text("Produit 16"),
                          Text("Produit 17"),
                          Text("Produit 18"),
                          Text("Produit 19"),
                          Text("Produit 20"),     Text("Produit 1"),
                          Text("Produit 2"),
                          Text("Produit 3"),
                          Text("Produit 4"),
                          Text("Produit 5"),
                          Text("Produit 6"),
                          Text("Produit 7"),
                          Text("Produit 8"),
                          Text("Produit 9"),
                          Text("Produit 10"),
                          Text("Produit 11"),
                          Text("Produit 12"),
                          Text("Produit 13"),
                          Text("Produit 14"),
                          Text("Produit 15"),
                          Text("Produit 16"),
                          Text("Produit 17"),
                          Text("Produit 18"),
                          Text("Produit 19"),
                          Text("Produit 20"),     Text("Produit 1"),
                          Text("Produit 2"),
                          Text("Produit 3"),
                          Text("Produit 4"),
                          Text("Produit 5"),
                          Text("Produit 6"),
                          Text("Produit 7"),
                          Text("Produit 8"),
                          Text("Produit 9"),
                          Text("Produit 10"),
                          Text("Produit 11"),
                          Text("Produit 12"),
                          Text("Produit 13"),
                          Text("Produit 14"),
                          Text("Produit 15"),
                          Text("Produit 16"),
                          Text("Produit 17"),
                          Text("Produit 18"),
                          Text("Produit 19"),
                          Text("Produit 20"),     Text("Produit 1"),
                          Text("Produit 2"),
                          Text("Produit 3"),
                          Text("Produit 4"),
                          Text("Produit 5"),
                          Text("Produit 6"),
                          Text("Produit 7"),
                          Text("Produit 8"),
                          Text("Produit 9"),
                          Text("Produit 10"),
                          Text("Produit 11"),
                          Text("Produit 12"),
                          Text("Produit 13"),
                          Text("Produit 14"),
                          Text("Produit 15"),
                          Text("Produit 16"),
                          Text("Produit 17"),
                          Text("Produit 18"),
                          Text("Produit 19"),
                          Text("Produit 20"),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
